library(readr)
tx2gene<-read_delim("Homo_sapiens.GRCh38.cdna.all.fa.tx2gene", delim=",", col_names=FALSE)
nrow(tx2gene)
tx2gene<-as.data.frame(tx2gene, stringsAsFactors=FALSE)
colnames(tx2gene)<-c("transcript_id", "gene_id")
idx<-grep("ENSG", tx2gene$gene_id)
all(length(idx)==nrow(tx2gene))
head(tx2gene)
saveRDS(tx2gene, "Homo_sapiens.GRCh38.cdna.all.fa.tx2gene.RDS")
